services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api/db.json:/app/db.json
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge